[package]
name = "bevy-ten-top"
version = "0.1.0"
authors = ["Blaine Price <blaine@ario.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"
bevy_window = "0.5.0"
petgraph = "0.5.1"